### ISSUE TITLE
NullPointerException in call to sendKeyChallengeForGemini

### ISSUE THREAD

**Issue by biell** [Nanoux/Onewave#10]
The app crashed today when sending a key challenge.  I think the periodic timer will sometimes hit when bluetooth is having an issue and this will occur.

Here is the error from logcat:

```
2019-12-27 12:01:14.146 13233-13233/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nanowheel.nanoux.nanowheel.pro.bugger, PID: 13233
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.nanowheel.nanoux.nanowheel.model.OWDevice.sendKeyChallengeForGemini(com.nanowheel.nanoux.nanowheel.util.BluetoothUtil)' on a null object reference
        at com.nanowheel.nanoux.nanowheel.util.BluetoothService$6.run(BluetoothService.java:329)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
2019-12-27 12:01:14.178 4470-5516/? W/MultiScreenManagerService: moveTaskBackToDisplayIfNeeded(): root activity or app is null, task=TaskRecord{3f1ccdc #17163 A=com.nanowheel.nanoux.nanowheel.pro.bugger U=0 StackId=1 sz=1}, rootActivity=null
```

A simple change to at least keep the app from crashing, and allowing it another opportunity to try again in 10 seconds is to check all the stuff to make sure nothing is null and change the `if` statement on line 327:

https://github.com/Nanoux/Onewave/blob/3cc96b52968d67d9888aeac4f605ad9020fe17f9/app/src/main/java/com/nanowheel/nanoux/nanowheel/util/BluetoothService.java#L326-L331

to something like the `if` statement on 322:

https://github.com/Nanoux/Onewave/blob/a87ce8104f1c27a4bf33b61b4522cd4ca200a2cc/app/src/main/java/com/nanowheel/nanoux/nanowheel/util/BluetoothService.java#L321-L326

You would probably want to try with the postDelayed looping statement inside the `if` clause.  I was worried that this might find you with no loopers at sometime.  But, I could be wrong.  Ultimately, I had implemented something to guarantee only one looper was running and it was always the latest.  It is possible that the issues I was seeing were to do with not having MainActivity launch in `singleTask` mode, which could be fixed by issue #8 .

My full version of this, with a guarantee that only one looper was running is:

https://github.com/Nanoux/Onewave/blob/6e08981fd077dd4809a43b870d850bc3af66bde7/app/src/main/java/com/nanowheel/nanoux/nanowheel/util/BluetoothService.java#L324-L333

**Comment by biell** [comment]
@Nanoux are you done with this codebase?  I am wanting to add CBXR support, but I am not sure if you have orphaned the project or not.

Thank you.
